name: Sync official collection
on:
  push:
    branches:
      - master
jobs:
  sync-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i --production
      - run: npm run sync official
        env:
          ALGOUX_API_TOKEN: ${{ secrets.ALGOUX_API_TOKEN }}
